### ISSUE TITLE
Is it time to just fork Yoast SEO?

### ISSUE THREAD

**Issue by reidbiztech** [senlin/so-clean-up-wp-seo#13]
Having just put this together:
https://wordpress.org/plugins/typing-lag-fix-for-yoast-seo/

And having just found your plugin. I am led to the question, 

Is it time to just fork Yoast SEO?

**Comment by senlin** [comment]
Hi thanks for your message. Interesting idea for a plugin. I hadn't noticed these things yet, but then again I don't use any of the things you describe that would cause such a lag :)

In December last year we tried forking the plugin. Many people were initially cheering, but the people that actually wanted to help putting the fork together was not enough to sustain development. 

It is a huge task to fork the plugin and then to keep it updated and bug free is another one. If you have time and resources, then by all means, go right ahead. I have since switched to [The SEO Framework](https://wordpress.org/plugins/autodescription/) plugin by @sybrew

**Comment by reidbiztech** [comment]
Ya, you'll only see the typing lag with Yoast SEO if working on a client computer with limited resources and when working on long complicated pages. That said, it is absolutely insane for Yoast SEO to be reloading and parsing shortcodes **on every single keystroke**. That decision alone is enough for me to want to abandon using it.

Interesting to hear that you guys were looking at a fork back in December. I'm not surprised. But no, I don't really have the time and resources to do it independently. And after thinking on it some more, it makes no sense to take something that is a mess and try to fix it instead of just starting fresh, which Sybre seems to have quite capably done.

Thank you very much for the tip on The SEO Framework! I am going to evaluate it and if satisfied, I will start replacing Yoast SEO on our sites with it as I work through my maintenance schedule.

**Comment by senlin** [comment]
The transition is very easy and painless when you use the SEO Data Transporter plugin. All the info about that is on the description, scroll down to "Transferring SEO data using SEO Data Transporter". I'm sure you'll like the plugin :)
