### ISSUE TITLE
Network activation

### ISSUE THREAD

**Issue by ryanhellyer** [senlin/so-clean-up-wp-seo#18]
Why does the plugin need to be activated network wide?

I have the Yoast plugin activated on some sites, but not all, but oddly I need to have the SO Clean up WP SEO plugin network activated. It seems strange to me.

**Comment by senlin** [comment]
Hi Ryan,

Thanks for review over at wp.org earlier and your question here.

As a matter of fact, @afragen just did a PR to (finally) make the plugin fully multisite compatible. In [his PR](https://github.com/senlin/so-clean-up-wp-seo/pull/16#issuecomment-235095814) we decided that since the plugin is basically for the admin of the site, it would be better to have only the settings show in the Network admin.

I guess we have not thought of a scenario that you now bring up where the Yoast plugin is installed on the the multisite network, but not activated on all of them.

Hmmm not really sure how to solve this or what the best way is to solve this. Of course it would be ideal that the plugin can be used without restrictions. 
At the same time I also don't want to go overboard with trying to it every possible scenario under the sun ;)

Any ideas welcome!

**Comment by ryanhellyer** [comment]
Since writing this, I realised a problem with doing it per site. I don't want to do the settings for the plugin on every individual site. I just want to do it once. So in that scenario, the settings should really be in the network admin.

You could add a per site options page, and if it's network activated, then have the network settings page override that. I'm not sure if that would create unnecessary work for you or not though.

After realising this scenario, I wouldn't actually use it per site anyway.

**Comment by afragen** [comment]
If the Yoast plugin isn't active on a subsite nothing really happens.

**Comment by ryanhellyer** [comment]
@afragen I see that. But it was just a little confusing initially, and it makes the plugin list look a bit weird when Yoast SEO is not network activated and this plugin is.

It's probably not worth changing it. I hadn't thought the scenario of having to set it every single time for each new site activation until after posting here.
