### ISSUE TITLE
Yoast Adds More bloat

### ISSUE THREAD

**Issue by jakejackson1** [senlin/so-clean-up-wp-seo#19]
Looks like a "Go Premium" sub menu has been added under the main SEO menu. I probably wouldn't have noticed it if it wasn't for the big orange star also included.

**Comment by senlin** [comment]
Hi Jake,
Thanks for your suggestion. Are you suggesting to include a setting that removes the star?

**Comment by jakejackson1** [comment]
A "Premium" tab specifically for upselling and provides no value to the open source plugin seems like bloat to me.

**Comment by senlin** [comment]
Hmmm, I find this a tricky one, especially since the [proposed guidelines](https://github.com/Ipstenu/wporg-plugin-guidelines/blob/master/guideline-11.md) sort of encourage in-plugin advertising for premium services.

The tab is not hijacking the dashboard or the rest of the plugin and you don't have to click on the tab as it clearly says what you can expect.

I am much more inclined to remove the star though as that is unnecessary attention seeking. 

Here's what I will do: I will add a new option that hides the red star by default and offers the option to hide the entire submenu.

Would that work for you?

**Comment by jakejackson1** [comment]
Sounds great. A setting to optionally disable that menu item would also be excellent and would compliment the other inline advertising you can disable. If I get some free time I'll look at a PR.
