### ISSUE TITLE
get it to work on Google Analytics van Yoast as wel?

### ISSUE THREAD

**Issue by webtaurus** [senlin/so-clean-up-wp-seo#2]
Hi Piet, like your plugin a lot... much as I like Yoast, I do not need to see him all over the place in the backend(s)... I'd rather have a drink with him at a WordCamp :-)
Maybe there is a way to make the adds disappear in his other plugins at the same time :-)

**Comment by senlin** [comment]
Hi @webtaurus so sorry for not replying sooner, I should receive notices from this, but I haven't.

I don't use Yoast's Google Analytics plugin, but that is a good idea indeed! 

It seems that with every release Team Yoast adds another *feature* to the plugin(s) and I keep adding stuff to mine to make that sh*t disappear again ;)

Instead of blanketing out everything, I am actually inclined to adding a settings page to the plugin and then I could also add in options for the Google Analytics plugin.

Would you perhaps be interested in helping adding a settings page?

**Comment by senlin** [comment]
@webtaurus sorry for the long silence.

I have decided to not pursue this as an integration. And since I don't use the Google Analytics of Yoast either (I don't even use GA), I would like to propose to instead fork my plugin and change it around so it hides the bloat for the other plugin. If you indeed fork my plugin, then please **don't forget to change the names of the functions** otherwise things will quickly fall apart...

closing this out now, but feel free to contact me if you have questions.
