### ISSUE TITLE
Hiding Yoast SEO from User Profile

### ISSUE THREAD

**Issue by jdalen** [senlin/so-clean-up-wp-seo#22]
Hi, I'd just like to leave a feature request  - I haven't been able to get either of these instructions working:
http://www.lubus.in/blog/wordpress-yoast-seo-hide-settings-user-profile-page-19

Ideally we would like to hide the Yoast SEO settings from the User Profiles - for our subscribers that login into the website:
Title to use for Author page
Meta description to use for Author page
and the three checkboxes.

Thanks!

**Comment by senlin** [comment]
Hi, thank for your message.

If I understand your request correctly, you would like to be able to have additional settings for your user-case scenario where you can hide the things you mention? 

In my opinion this has nothing to do with bloat the Yoast SEO plugin adds to a site, but is something bespoke that you would like to have for your site. Unless I receive heaps of other requests for this, it is highly unlikely I will ever add this to the plugin.

Most likely the reason that you didn't get the aforementioned instructions to work is because something has changed in the backend. I just had a look and if you change the CSS instruction of the lubus.in site into the following, then it works fine.
```
.profile-php .yoast.yoast-settings {
    display: none;
}
```

Hope this helps.

**Comment by jdalen** [comment]
Hi Piet,

Yes, this helps very much!!  Thank you for your time looking into this 
for me.  Very much appreciated!

Jessica
