### ISSUE TITLE
Can't hide "# links in article" (wpseo-links) column

### ISSUE THREAD

**Issue by shadowshades** [senlin/so-clean-up-wp-seo#36]
Everthing is checked on my Hide Bloat Settings, but can't hide one column, see capture below :

![capture](https://user-images.githubusercontent.com/8053423/31408105-6757eabc-add5-11e7-910a-6b626e58c8c0.png)

Thanks!

**Comment by senlin** [comment]
Hi Shad, thanks for posting this issue.
Can you please be a bit more elaborate as I have no idea what you mean exactly.
Thanks,
Piet

**Comment by shadowshades** [comment]
Seem that Yoast SEO added a column named **wpseo-links**. Inside your plugin setting, I dont find any option to hide this column. See Column capture on my first message. Thanks! :)

**Comment by senlin** [comment]
The column capture of your first message is not clear, hence my question for clarification...

You are using Yoast SEO 5.6? 
Which version of Hide SEO Bloat are you using? 
On one of the dev sites I use to test things, I cannot replicate your issue, I cannot see a column named wpseo-links. In which screens does this column show? Can you do a screenshot of the entire screen perhaps?
Thanks,
Piet

**Comment by senlin** [comment]
Ah, finally I understand what you mean!

As it turns out, the Yoast SEO Settings already have a disable/enable setting in place for this Text Link Counter as you can see at the bottom of `[your-site-url]/wp-admin/admin.php?page=wpseo_dashboard#top#features`.

As with other options that can be set in the plugin itself - **and** because this option is disabled by default - we have decided not to add it as a setting to the Hide SEO Bloat plugin. 

Thanks for your understanding!
Piet

**Comment by shadowshades** [comment]
Thanks for your answer!

Le 10 oct. 2017 à 16:49, Piet Bos <notifications@github.com<mailto:notifications@github.com>> a écrit :


Ah, finally I understand what you mean!

As it turns out, the Yoast SEO Settings already have a disable/enable setting in place for this Text Link Counter as you can see at the bottom of [your-site-url]/wp-admin/admin.php?page=wpseo_dashboard#top#features.

As with other options that can be set in the plugin itself - and because this option is disabled by default - we have decided not to add it as a setting to the Hide SEO Bloat plugin.

Thanks for your understanding!
Piet
