### ISSUE TITLE
Admin Bar

### ISSUE THREAD

**Issue by tkes** [senlin/so-clean-up-wp-seo#9]
The feature *removes the Yoast SEO settings from the Admin Bar* works fine, but with 2.3.5/1.7.2 still a `SEO` entry appears in Admin Bar, which has some links to keyword research resources, `id=wp-admin-bar-wpseo-kwresearch`.

Can you add removal of whole SEO entry in Admin Bar?

Thanks for the plugin.

**Comment by senlin** [comment]
That entry we left on purpose, because it is not specific about Yoast SEO, but more generally catered towards SEO.

If you want to remove them, then I would like to suggest to remove them via the functions.php file of your theme. We have added the options to our plugin, but commented them out, so you can easily find them: https://github.com/senlin/so-clean-up-wp-seo/blob/master/so-clean-up-wp-seo.php#L105-L118

Later on when we add a settings page to the plugin, this will become an option.

**Comment by tkes** [comment]
Thanks for quick feedback.

PS. Would suggest to use `remove_menu(..)` for Admin Bar items, instead of `remove_node(..)` as in your commented code, internally both do (at the moment) the same thing but the plugin uses `add_menu(..)` for these items, so `remove_menu(..)` somehow "feels" more correct.

**Comment by senlin** [comment]
except that `remove_menu` doesn't work and `remove_node` does :)

**Comment by tkes** [comment]
Strange, `remove_menu` works fine here in Admin Bar.

Which version of WordPress are you using? In [WP 4.3.1 Admin Bar class](https://core.trac.wordpress.org/browser/tags/4.3.1/src/wp-includes/class-wp-admin-bar.php#L86) `remove_menu` just calls `remove_node`, would be interesting, why it does not work for you.

**Comment by senlin** [comment]
if `remove_menu` calls `remove_node`, then why would we be using `remove_menu` in the first place? ;)
